name: sportquiz
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_inappwebview: ^5.7.2+3
  device_info: ^2.0.3
  firebase_core: ^2.15.0
  firebase_remote_config: ^4.2.4
  check_vpn_connection: ^0.0.2
  shared_preferences: ^2.0.10
  http: ^0.13.5
  html_unescape: ^2.0.0
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/flutter_logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/background.png