// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQWRITNvqBt3NVOjpd9BaHCmRsFLAiIXQ',
    appId: '1:159590557612:web:76e51096c507ec25f83c09',
    messagingSenderId: '159590557612',
    projectId: 'sportquiz-remote-config',
    authDomain: 'sportquiz-remote-config.firebaseapp.com',
    storageBucket: 'sportquiz-remote-config.appspot.com',
    measurementId: 'G-0HEGEHKK5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhSUL_yEuhgGOLHEYC_3aFUnLc6OtLiIc',
    appId: '1:159590557612:android:f01ef94c1e623354f83c09',
    messagingSenderId: '159590557612',
    projectId: 'sportquiz-remote-config',
    storageBucket: 'sportquiz-remote-config.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAidVJqQIsbRuAlZN89ijZ9PWhCMlJrJZw',
    appId: '1:159590557612:ios:cecfbfcd07fbc271f83c09',
    messagingSenderId: '159590557612',
    projectId: 'sportquiz-remote-config',
    storageBucket: 'sportquiz-remote-config.appspot.com',
    iosClientId: '159590557612-h8ss0ohiej02knrd2c9sd26bfda7skq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAidVJqQIsbRuAlZN89ijZ9PWhCMlJrJZw',
    appId: '1:159590557612:ios:895fc5cd7ed03e87f83c09',
    messagingSenderId: '159590557612',
    projectId: 'sportquiz-remote-config',
    storageBucket: 'sportquiz-remote-config.appspot.com',
    iosClientId: '159590557612-dk2r4hnsri4teijo02orkuffcrkp8t2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportquiz.RunnerTests',
  );
}
